name: Build and do artifact stuff on PR
on:
  # This workflow will only run for pull requests targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.number }}
    steps:
      # Remember we have to check out the repository first!
      - name: Checkout repository
        uses: actions/checkout@v5

      # This step installs the dependencies
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: Get version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "number=$VERSION" >> $GITHUB_OUTPUT
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-v${{ steps.version.outputs.number }}
          path: dist/
          retention-days: 5

  test:
     name: Test project
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Checkout
         uses: actions/checkout@v5
       - name: Download build
         uses: actions/download-artifact@v4
         with:
           name: build-v${{ needs.build.outputs.version }}
           path: dist/
       - name: Test
         run: npm run test:full-report
       - name: upload coverage report
         if: always ()
         uses: actions/upload-artifact@v4
         with:
          name: coverage-report
          path: coverage/
          retention-days: 30
  report:
    name: Build report
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Download buildfiles
        uses: actions/download-artifact@v4
        with:
          name: build-v${{ needs.build.outputs.version }}
          path: dist/
      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage/
      - name: list buildfiles and coverage
        run: |
          echo $(ls -la dist/)
          echo $(ls -la coverage/)
          echo "Build and test artifacts collected"
