name: Comment test coverage
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm install

      # Write test coverage output to a file
      - name: Run tests with coverage
        run: |
          npm run test:short-report > coverage-output.txt 2>&1

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-output.txt
          retention-days: 1

  comment:
    # Wait for the 'test' job to complete
    needs: test

    runs-on: ubuntu-latest
    steps:
      # Download the coverage report artifact from the 'test' job,
      # storing it as a file on the runner
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      # Read the coverage report into memory
      - name: Read coverage report
        id: coverage
        run: |
          echo "COVERAGE_REPORT<<EOF" >> $GITHUB_OUTPUT
          cat coverage-output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Find comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: <!-- coverage-report -->

      - name: Post coverage comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Test Coverage Report

            ```
            ${{ steps.coverage.outputs.COVERAGE_REPORT }}
            ```

            ---
            *Coverage report generated by GitHub Actions*
            <!-- coverage-report -->
          edit-mode: replace