name: Test output
on:
  # This workflow will only run for pull requests targeting the main branch
  push:

jobs:
  info:
    name: Gather info
    runs-on: ubuntu-latest
    steps:

      - name: Get current SHA
        id: sha
        run: | 
          sha=$(git rev-parse --short HEAD)
          echo "SHA=$sha" >> $GITHUB_OUTPUT
      - name: Get current branch name
        id: branch-name
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo "branch=$branch" >> $GITHUB_OUTPUT
      - name: Get commit message
        id: commit-msg
        run: |
          message=$(git log -1 --pretty=%B)
          echo "Commitmessage=$message" >> $GITHUB_OUTPUT

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: info
    steps:
      # Remember we have to check out the repository first!
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get node version
        id: node-version
        run: |
          nodeversion = $(node --version)
          echo "nodeversion=$nodeversion" >> $GITHUB_OUTPUT
      - name: Get npm version
        id: npm-version
        run: |
          npmversion = $(npm --version)
          echo "npmversion=$npmversion" >> $GITHUB_OUTPUT
      # This step installs the dependencies
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Output message
        run: echo "Building commit ${{ needs.info.outputs.sha }} on branch ${{ needs.info.outputs.branch-name }}
      - name: generate report
        id: report
        run: |
          echo "--- Build report ---"
          echo "Node version: ${{ steps.node-version.outputs.nodeversion }}"
          echo "NPM version: ${{ steps.npm-version.outputs.npmversion }}"
          echo "Success!" >> $GITHUB_OUTPUT
  summary:
    name: Write Summary
    runs-on: ubuntu-latest
    needs: [info, build]
    steps:
      - name: Output summary
        run: |
          echo "${{ needs.build.outputs.report }}"
          

